// Generated by CoffeeScript 1.8.0
(function() {
  var LinkedList, counter;

  counter = 0;

  module.exports = LinkedList = {
    init: function(list, id) {
      if (id == null) {
        id = counter += 1;
      }
      list._prevProp = "_llistPrev" + id;
      list._nextProp = "_llistNext" + id;
      list[list._nextProp] = list;
      return list[list._prevProp] = list;
    },
    peek: function(list) {
      var item;
      item = list[list._prevProp];
      if (item !== list) {
        return item;
      }
    },
    shift: function(list) {
      return LinkedList.remove(list, list[list._prevProp]);
    },
    remove: function(list, item) {
      if (item[list._nextProp]) {
        item[list._nextProp][list._prevProp] = item[list._prevProp];
      }
      if (item[list._prevProp]) {
        item[list._prevProp][list._nextProp] = item[list._nextProp];
      }
      item[list._nextProp] = null;
      item[list._prevProp] = null;
      return item;
    },
    append: function(list, item) {
      LinkedList.remove(list, item);
      item[list._nextProp] = list[list._nextProp];
      list[list._nextProp][list._prevProp] = item;
      item[list._prevProp] = list;
      list[list._nextProp] = item;
    },
    isEmpty: function(list) {
      return list[list._nextProp] === list;
    }
  };

}).call(this);
