// Generated by CoffeeScript 1.8.0
(function() {
  var LinkedList, shared_examples;

  LinkedList = require('../linked_list');

  shared_examples = require('./linked_list_shared');

  shared_examples(LinkedList);

}).call(this);
